"""solvax: differentiable structured linear solvers and matrix-free methods in JAX.

Generic solver infrastructure for kinetic and PDE codes: batched structured
direct solves, preconditioned/recycled Krylov methods, checkpointed recurrences,
memory-chunked autodiff, and implicit differentiation. Primal kernels compose
with JAX transformations; derivative entry points state whether they use a
taped, implicit, checkpointed, localized, or reverse-only rule.
"""

from solvax.autodiff import (
    auto_chunk_size,
    checkpointed_fori_loop,
    chunk_map,
    chunked_jacfwd,
    chunked_jacobian,
    chunked_jacrev,
)
from solvax.banded import (
    BandedLUFactors,
    PeriodicBandedLUFactors,
    banded_matvec,
    lu_factor_banded,
    lu_factor_banded_periodic,
    lu_solve_banded,
    lu_solve_banded_periodic,
)
from solvax.direct import (
    BlockTridiagFactors,
    ChainWindowPlan,
    GeneratedBlockTridiagFactors,
    LocalizationWindow,
    block_thomas,
    block_thomas_checkpointed_fn,
    block_thomas_factor,
    block_thomas_factor_fn,
    block_thomas_selected_tail_fn,
    block_thomas_solve,
    block_thomas_truncated,
    block_thomas_truncated_fn,
    block_thomas_truncated_fn_with_residual,
    block_tridiag_matvec,
    block_tridiag_relative_residual,
    certified_adjoint_window,
    check_localized_gradient,
    localization_crossover_window,
    localization_profile_fn,
    mixed_precision_block_thomas,
    plan_chain_windows,
    suggest_adjoint_window,
)
from solvax.eigen import eigenpair_reverse
from solvax.elliptic import (
    FourierHelmholtzOperator,
    build_fourier_helmholtz_operator,
    periodic_poisson_eigenvalues,
    solve_fourier_helmholtz,
    solve_periodic_poisson,
    solve_periodic_poisson_spectral,
)
from solvax.fixed_point import (
    FixedPointSolution,
    affine_fixed_point_gmres,
    aitken_fixed_point,
    aitken_relaxation,
    anderson_mixing,
    anderson_weights,
    fixed_point_iteration,
)
from solvax.implicit import (
    NewtonKrylovSolution,
    linear_solve,
    newton_krylov,
    recycled_linear_solve,
    root_solve,
)
from solvax.krylov import RECYCLE_DRIFT_ADVISORY, KrylovSolution, gcrot, gmres
from solvax.native import SpluFactorization, splu_solve
from solvax.native_eigen import (
    SparseEigenSolution,
    sparse_eigenpairs,
    sparse_operator_matrix,
)
from solvax.nonlinear import (
    ContinuationConfig,
    ContinuationSolution,
    ContinuationStep,
    PseudoTransientConfig,
    PseudoTransientHistory,
    PseudoTransientSolution,
    adaptive_continuation,
    eisenstat_walker_forcing,
    pseudo_arclength_corrector,
    pseudo_arclength_residual,
    pseudo_transient_continuation,
)
from solvax.operators import (
    BlockTridiagonalOperator,
    BorderedOperator,
    KroneckerOperator,
    MatrixFreeOperator,
    SumOperator,
    schur_projected_precond,
)
from solvax.parallel import axis_inner_product, shard_batch
from solvax.pcg import PCGDiagnostics, PCGSolution, pcg, pcg_linear_solve, status_name
from solvax.precond import (
    MultigridHierarchy,
    MultigridLevel,
    additive_preconditioner,
    additive_tridiagonal_line_preconditioner,
    alfven_block,
    block_jacobi,
    coarse_operator,
    dense_coarse_solve,
    galerkin_deflation,
    jacobi,
    kronecker_nkp,
    line_smoother,
    low_rank_corrected,
    mixed_precision,
    multigrid,
    nearest_kronecker,
    p_multigrid,
    semicoarsening_hierarchy,
)
from solvax.propagator import (
    AdaptiveEigenSolution,
    PropagatorEigenSolution,
    RK4Timestep,
    adaptive_eigenpair,
    estimate_rk4_timestep,
    exponential_eigenpairs,
    propagator_eigenpairs,
)
from solvax.randomized import (
    nystrom_preconditioner,
    nystrom_preconditioner_adaptive,
)
from solvax.refine import as_low_precision, iterative_refinement
from solvax.smoothers import (
    alternating_smoother,
    block_jacobi_smoother,
    high_frequency_mask,
    jacobi_smoother,
    plane_smoother,
    relaxation,
    smoothing_factor,
    tridiagonal_smoother,
    upwind_smoother,
)
from solvax.transfer import (
    CoarseningPlan,
    coarse_axis_size,
    coarse_grid_shape,
    coarsenable,
    coarsening_plan,
    grid_transfer,
    prolongation_matrix,
    restriction_matrix,
)
from solvax.tridiagonal import (
    TridiagonalSolveDiagnostics,
    TridiagonalSolveResult,
    cyclic_tridiagonal_solve,
    tridiagonal_solve,
    tridiagonal_solve_checked,
)

__version__ = "0.18.0"

__all__ = [
    "RECYCLE_DRIFT_ADVISORY",
    "BandedLUFactors",
    "AdaptiveEigenSolution",
    "PropagatorEigenSolution",
    "PeriodicBandedLUFactors",
    "RK4Timestep",
    "adaptive_eigenpair",
    "propagator_eigenpairs",
    "banded_matvec",
    "lu_factor_banded",
    "lu_factor_banded_periodic",
    "lu_solve_banded",
    "lu_solve_banded_periodic",
    "BlockTridiagFactors",
    "GeneratedBlockTridiagFactors",
    "block_tridiag_matvec",
    "block_tridiag_relative_residual",
    "eigenpair_reverse",
    "estimate_rk4_timestep",
    "exponential_eigenpairs",
    "block_thomas",
    "ChainWindowPlan",
    "certified_adjoint_window",
    "block_thomas_checkpointed_fn",
    "block_thomas_factor",
    "block_thomas_factor_fn",
    "block_thomas_solve",
    "block_thomas_selected_tail_fn",
    "block_thomas_truncated",
    "block_thomas_truncated_fn",
    "localization_profile_fn",
    "LocalizationWindow",
    "check_localized_gradient",
    "localization_crossover_window",
    "plan_chain_windows",
    "suggest_adjoint_window",
    "block_thomas_truncated_fn_with_residual",
    "mixed_precision_block_thomas",
    "FourierHelmholtzOperator",
    "build_fourier_helmholtz_operator",
    "periodic_poisson_eigenvalues",
    "solve_fourier_helmholtz",
    "solve_periodic_poisson",
    "solve_periodic_poisson_spectral",
    "tridiagonal_solve",
    "tridiagonal_solve_checked",
    "TridiagonalSolveDiagnostics",
    "TridiagonalSolveResult",
    "cyclic_tridiagonal_solve",
    "FixedPointSolution",
    "affine_fixed_point_gmres",
    "aitken_fixed_point",
    "aitken_relaxation",
    "anderson_mixing",
    "anderson_weights",
    "fixed_point_iteration",
    "KrylovSolution",
    "gmres",
    "gcrot",
    "PCGSolution",
    "PCGDiagnostics",
    "pcg",
    "pcg_linear_solve",
    "status_name",
    "linear_solve",
    "recycled_linear_solve",
    "NewtonKrylovSolution",
    "newton_krylov",
    "root_solve",
    "ContinuationConfig",
    "ContinuationSolution",
    "ContinuationStep",
    "PseudoTransientConfig",
    "PseudoTransientHistory",
    "PseudoTransientSolution",
    "adaptive_continuation",
    "eisenstat_walker_forcing",
    "pseudo_arclength_corrector",
    "pseudo_arclength_residual",
    "pseudo_transient_continuation",
    "MatrixFreeOperator",
    "SumOperator",
    "KroneckerOperator",
    "BlockTridiagonalOperator",
    "BorderedOperator",
    "schur_projected_precond",
    "shard_batch",
    "additive_preconditioner",
    "alfven_block",
    "axis_inner_product",
    "additive_tridiagonal_line_preconditioner",
    "jacobi",
    "block_jacobi",
    "coarse_operator",
    "dense_coarse_solve",
    "galerkin_deflation",
    "line_smoother",
    "low_rank_corrected",
    "multigrid",
    "p_multigrid",
    "MultigridLevel",
    "MultigridHierarchy",
    "semicoarsening_hierarchy",
    "CoarseningPlan",
    "coarse_axis_size",
    "coarse_grid_shape",
    "coarsenable",
    "coarsening_plan",
    "grid_transfer",
    "restriction_matrix",
    "prolongation_matrix",
    "relaxation",
    "jacobi_smoother",
    "block_jacobi_smoother",
    "tridiagonal_smoother",
    "upwind_smoother",
    "plane_smoother",
    "alternating_smoother",
    "high_frequency_mask",
    "smoothing_factor",
    "mixed_precision",
    "kronecker_nkp",
    "nearest_kronecker",
    "nystrom_preconditioner",
    "nystrom_preconditioner_adaptive",
    "iterative_refinement",
    "as_low_precision",
    "chunk_map",
    "auto_chunk_size",
    "checkpointed_fori_loop",
    "chunked_jacfwd",
    "chunked_jacrev",
    "chunked_jacobian",
    "SpluFactorization",
    "SparseEigenSolution",
    "splu_solve",
    "sparse_eigenpairs",
    "sparse_operator_matrix",
    "__version__",
]
